LABEL build_version="Premiumizearr version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="JackDallas"

EXPOSE 8182

WORKDIR /

RUN ls

RUN mkdir /data && \
    mkdir /unzip && \
    mkdir /downloads && \
    mkdir /transfers && \
    mkdir /blackhole && \
    mkdir -p /opt/app/

WORKDIR /opt/app/

ENV PREMIUMIZEARR_CONFIG_DIR_PATH=/data
ENV PREMIUMIZEARR_LOGGING_DIR_PATH=/data

COPY premiumizearrd /opt/app/
COPY build/static /opt/app/static

ENTRYPOINT ["/opt/app/premiumizearrd"]